version: '2'
services:
    web-build:
        build: 
            context: .
            dockerfile: BuildDockerFile
        image: "webbuild:base"
        tty: true
        working_dir: /app
        ports:
            - "8080:8080"
        volumes:
            -  "./src:/app"
        command: sh /app/build.sh
    rabbitmq:
        build:
            context: .
            dockerfile: RabbitDockerFile
        image: webbuild:rabbitmq-3-management
        hostname: someRabbit
        restart: always
        tty: true
        volumes:
            - /var/lib/rabbitmq
        env_file: .env
        ports:
            - "5672:5672"
            - "15672:15672"
            - "61613:61613"
        expose:
            - "5672"
            - "15672"
            - "61613"
        logging:
            driver: "json-file"
